### ISSUE TITLE
The model *pth is your trained? or convert from official tensorflow tflite?

### ISSUE THREAD

**Issue by xuanyuyt** [lhwcv/mlsd_pytorch#1]
Hi~, such as title, I want to know the answer to determine if it is easy to reproduce. thank you!

**Comment by lhwcv** [comment]
@xuanyuyt  Hi.  converted from TFLite.  I also plan to reproduce, when get a result,  I'll push the trainging code.

**Comment by smitheric95** [comment]
Hi @lhwcv, could you share some info on how you converted the TFLite model to a `.pth` file? I would like to do the same for an older version of PyTorch.

(Great work, by the way!)

**Comment by xuanyuyt** [comment]
> @xuanyuyt Hi. converted from TFLite. I also plan to reproduce, when get a result, I'll push the trainging code.

Thank you for your reply !

**Comment by lhwcv** [comment]
@smitheric95  Hi,  thank you first.
I don't found an ease-to-use tool convert the model from tflite to Pytorch.
So wirte a network strictly according TFlite one, and use tflite + numpy to get the weight can be a choice.

Already push  convert demo, you can see in convert/

**Comment by smitheric95** [comment]
@lhwcv, I was able to successfully convert the TFLite model to `.pth` using your notebook in `convert/`. 

Thank you very much!!

**Comment by zctang** [comment]
TypeError: __init__() missing 1 required positional argument: 'cfg'。when i use training model： best.pth（trained 83epoch）to do the inference. it occur this error.

**Comment by zctang** [comment]
@lhwcv Thanks for your great job. I can train the model. but when i do the inference with the trained model. the error occur: TypeError: init() missing 1 required positional argument: 'cfg'。when i use training model： best.pth（trained 83epoch）to do the inference. it occur this error. what's wrong with my code?
