### ISSUE TITLE
performance speed 

### ISSUE THREAD

**Issue by hirokic5** [lhwcv/mlsd_pytorch#10]
Thanks for your great repository !!! 

I ran demo.py, and measured large model performance speed, it resulted in **almost 12FPS on RTX 2080Ti.** 
Codes likes below:
```
import time
torch.cuda.synchronize()
start=time.time()
img = cv2.imread(img_fn)
img = cv2.resize(img, (512, 512))

img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
lines = pred_lines(img, model, [512, 512], 0.1, 20)
img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)

for l in lines:
    cv2.line(img, (int(l[0]), int(l[1])), (int(l[2]), int(l[3])), (0,200,200), 1,16)
    
torch.cuda.synchronize()
time.time()-start
# 0.0828
```

So, in your environment, how fast does large model work ?? (and I'd like to know your GPU envirnoment ).

**Comment by lhwcv** [comment]
@hirokic5 Almost the same with yours, I guess  the high performance result reported in the official paper only  include the network inference time.

**Comment by hirokic5** [comment]
Thanks your reply ! I understood.

**Comment by JinraeKim** [comment]
> @hirokic5 Almost the same with yours, I guess the high performance result reported in the official paper only include the network inference time.

It's also similar to me (even slower).
What does "the inference time" mean?
For only a single line, or a single execution of `pred_lines`?
