### ISSUE TITLE
怎么得到数据集那样格式的json文件呢？

### ISSUE THREAD

**Issue by chenenp** [lhwcv/mlsd_pytorch#18]

**Comment by lhwcv** [comment]
你可以参考这里：  https://github.com/cherubicXN/afm_cvpr2019

**Comment by chenenp** [comment]
非常感谢您的答复，还有我在训练和测试过程中碰到加载权重字典却无法匹配模型形状的问题。请问该如何解决了呢？

**Comment by lhwcv** [comment]
@chenenp  有详细的错误和截图吗

**Comment by chenenp** [comment]
RuntimeError: Error(s) in loading state_dict for Mobilev2_mlsd_tiny
	size mismatch for module.backbone.feat..: copying a param with shape torch.Size([32, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size(32,4,3,3)
大概就是这个样子类型的错误

**Comment by lhwcv** [comment]
@chenenp  检查你模型使用的python module，如果是自己训练的，要使用./mlsd_pytorch/models 下的， 而非./models/下。   这个仓库训练使用的是RGB 的， 但是原版为了GPU友好， 是 RGBA 的， 所以是4 个通道。

**Comment by chenenp** [comment]
![image](https://user-images.githubusercontent.com/82936409/184562085-902d0c8f-1418-4b47-bea3-6536221dfa69.png)
可是demo里面你们的代码用的就是./的模型呢？

**Comment by lhwcv** [comment]
@chenenp  外面一层的是转换自TF 的。 如果你自己训练了模型， 使用：  python mlsd_pytorch/pred_and_eval_sAP.py  试下。

**Comment by chenenp** [comment]
@lhwcv 好的，非常感谢。对于您给我提供的另外一篇论文中数据标注格式转换的问题，如何制作自己数据的线段标注.pkl数据格式文件呢？
