### ISSUE TITLE
export onnx: load the model size not same 

### ISSUE THREAD

**Issue by XDxiaoqi** [lhwcv/mlsd_pytorch#24]
hi~,
     the env is: ubuntu20, cuda11.6, pytorch13
     finish the training, use the save latest.pth file to export onnx, but something is wrong
     can help to give some advices?

model.load_state_dict(torch.load(model_path), strict=True)
Error(s) in loading state_dict for MobileV2_MLSD_Large:
	size mismatch for backbone.features.0.0.weight: copying a param with shape torch.Size([32, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 4, 3, 3]).

**Comment by XDxiaoqi** [comment]
the mbv2_mlsd_large.py is different in diff folder

**Comment by duyouzhi** [comment]
请问这个问题你解决了吗？预训练模型是四通道的，但是自己的自定义数据集图像又是三通道的。
